<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\..\ServiceDefaults\Lagerkraft.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\Shared\Lagerkraft.Shared.csproj" />
    <ProjectReference Include="..\Inventory\Lagerkraft.WmsCore.Inventory.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NATS.Net" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>
</Project>


