import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const frontendRoot = join(here, "..");
const openapiDir = join(frontendRoot, "..", "contracts", "openapi");
const outDir = join(frontendRoot, "packages", "api-client", "src", "generated");

await mkdir(outDir, { recursive: true });

const files = (await readdir(openapiDir)).filter((name) => name.endsWith(".json")).sort();
for (const file of files) {
  const spec = (await readFile(join(openapiDir, file), "utf8")).replace(/^\uFEFF/, "");
  const ast = await openapiTS(spec);
  const dest = join(outDir, `${file.slice(0, -5)}.ts`);
  await writeFile(dest, `// Generated by scripts/gen-api.mjs. Do not edit.\n${astToString(ast)}`);
  console.log(`Wrote ${dest}`);
}
