using System.Globalization;
using System.Reflection;
using System.Text;
using Lagerkraft.Shared;

var dest = args.Length > 0
    ? args[0]
    : Path.Combine("packages", "domain", "src", "generated", "permissions.ts");

var roles = new[]
{
    Permissions.TenantAdmin,
    Permissions.WarehouseManager,
    Permissions.FloorWorker,
    Permissions.Viewer,
};

var sb = new StringBuilder();
sb.AppendLine("// Generated by frontend/tools/gen-permissions. Do not edit.");
sb.AppendLine();
sb.AppendLine(CultureInfo.InvariantCulture, $"export const MAP_VERSION = {Permissions.MapVersion} as const;");
sb.AppendLine();
sb.AppendLine("export const ROLES = {");
foreach (var field in RoleConstFields())
{
    var value = (string)field.GetRawConstantValue()!;
    sb.AppendLine(CultureInfo.InvariantCulture, $"  {field.Name}: \"{value}\",");
}

sb.AppendLine("} as const;");
sb.AppendLine();
sb.AppendLine("export const PERMISSIONS = {");
foreach (var field in PermissionConstFields())
{
    var value = (string)field.GetRawConstantValue()!;
    sb.AppendLine(CultureInfo.InvariantCulture, $"  {field.Name}: \"{value}\",");
}

sb.AppendLine("} as const;");
sb.AppendLine();
sb.AppendLine("export const ROLE_PERMISSIONS: Record<string, readonly string[]> = {");
foreach (var role in roles)
{
    sb.AppendLine(CultureInfo.InvariantCulture, $"  \"{role}\": [");
    foreach (var permission in Permissions.ForRole(role).OrderBy(p => p, StringComparer.Ordinal))
    {
        sb.AppendLine(CultureInfo.InvariantCulture, $"    \"{permission}\",");
    }

    sb.AppendLine("  ],");
}

sb.AppendLine("};");
sb.AppendLine();

Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(dest))!);
File.WriteAllText(dest, sb.ToString());
Console.WriteLine($"Wrote {dest}");

static IEnumerable<FieldInfo> StringConsts() =>
    typeof(Permissions)
        .GetFields(BindingFlags.Public | BindingFlags.Static)
        .Where(f => f is { IsLiteral: true, IsInitOnly: false } && f.FieldType == typeof(string))
        .OrderBy(f => f.MetadataToken);

static IEnumerable<FieldInfo> RoleConstFields() =>
    StringConsts().Where(f => ((string)f.GetRawConstantValue()!).IndexOf('.') < 0);

static IEnumerable<FieldInfo> PermissionConstFields() =>
    StringConsts().Where(f => ((string)f.GetRawConstantValue()!).IndexOf('.') >= 0);
