// <auto-generated />
using System;
using Lagerkraft.WmsCore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lagerkraft.WmsCore.Api.Data.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260919102902_InventoryTables")]
    partial class InventoryTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "ltree");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowLoosePick")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_loose_pick");

                    b.Property<Guid>("BaseUomId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_uom_id");

                    b.Property<bool>("CatchWeight")
                        .HasColumnType("boolean")
                        .HasColumnName("catch_weight");

                    b.Property<Guid?>("CatchWeightUomId")
                        .HasColumnType("uuid")
                        .HasColumnName("catch_weight_uom_id");

                    b.Property<string>("Gtin")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("gtin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OrderMultipleLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_multiple_level_id");

                    b.Property<string>("PickInstruction")
                        .HasColumnType("text")
                        .HasColumnName("pick_instruction");

                    b.Property<int>("QuantityPrecision")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_precision");

                    b.Property<decimal>("QuantityStep")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity_step");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int?>("WeightPerBaseUnitG")
                        .HasColumnType("integer")
                        .HasColumnName("weight_per_base_unit_g");

                    b.HasKey("Id")
                        .HasName("pk_article");

                    b.HasIndex("BaseUomId")
                        .HasDatabaseName("ix_article_base_uom_id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_article_sku");

                    b.ToTable("article", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.ChangeLogRow", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Seq"));

                    b.Property<Guid?>("Actor")
                        .HasColumnType("uuid")
                        .HasColumnName("actor");

                    b.Property<Guid?>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Op")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("op");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Seq")
                        .HasName("pk_change_log");

                    b.ToTable("change_log", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.Deviation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.HasKey("Id")
                        .HasName("pk_deviation");

                    b.ToTable("deviation", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.HandlingUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("HeightMm")
                        .HasColumnType("integer")
                        .HasColumnName("height_mm");

                    b.Property<string>("Lpn")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("lpn");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_handling_unit");

                    b.HasIndex("WarehouseId", "Lpn")
                        .IsUnique()
                        .HasDatabaseName("ix_handling_unit_warehouse_id_lpn");

                    b.ToTable("handling_unit", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.HandlingUnitContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<Guid>("HandlingUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("handling_unit_id");

                    b.Property<Guid>("PackagingLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("packaging_level_id");

                    b.Property<decimal>("QtyBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("qty_base");

                    b.HasKey("Id")
                        .HasName("pk_handling_unit_content");

                    b.HasIndex("HandlingUnitId", "ArticleId")
                        .IsUnique()
                        .HasDatabaseName("ix_handling_unit_content_handling_unit_id_article_id");

                    b.ToTable("handling_unit_content", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("barcode");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<int?>("DepthMm")
                        .HasColumnType("integer")
                        .HasColumnName("depth_mm");

                    b.Property<int?>("HeightMm")
                        .HasColumnType("integer")
                        .HasColumnName("height_mm");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<int?>("MaxWeightG")
                        .HasColumnType("integer")
                        .HasColumnName("max_weight_g");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("ltree")
                        .HasColumnName("path");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<int?>("WidthMm")
                        .HasColumnType("integer")
                        .HasColumnName("width_mm");

                    b.HasKey("Id")
                        .HasName("pk_location");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_location_warehouse_id_code");

                    b.HasIndex("WarehouseId", "ParentId")
                        .HasDatabaseName("ix_location_warehouse_id_parent_id");

                    b.ToTable("location", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.LocationReservation", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("LocationId")
                        .HasName("pk_location_reservation");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_location_reservation_expires_at");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_location_reservation_task_id");

                    b.ToTable("location_reservation", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.OutboxRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_outbox_published_at");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.PackagingLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("barcode");

                    b.Property<int>("DepthMm")
                        .HasColumnType("integer")
                        .HasColumnName("depth_mm");

                    b.Property<int>("GrossWeightG")
                        .HasColumnType("integer")
                        .HasColumnName("gross_weight_g");

                    b.Property<int>("HeightMm")
                        .HasColumnType("integer")
                        .HasColumnName("height_mm");

                    b.Property<bool>("IsBreakable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_breakable");

                    b.Property<bool>("IsDefaultReceiving")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default_receiving");

                    b.Property<bool>("IsDefaultShipping")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default_shipping");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PalletTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("pallet_type_id");

                    b.Property<decimal>("QtyInBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("qty_in_base");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<int>("WidthMm")
                        .HasColumnType("integer")
                        .HasColumnName("width_mm");

                    b.HasKey("Id")
                        .HasName("pk_packaging_level");

                    b.HasIndex("ArticleId", "Rank")
                        .IsUnique()
                        .HasDatabaseName("ix_packaging_level_article_id_rank");

                    b.ToTable("packaging_level", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.ProcessedCommand", b =>
                {
                    b.Property<Guid>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.HasKey("CommandId")
                        .HasName("pk_processed_commands");

                    b.ToTable("processed_commands", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.ProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.HasKey("EventId", "Consumer")
                        .HasName("pk_processed_events");

                    b.ToTable("processed_events", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.StockBalance", b =>
                {
                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<Guid>("HandlingUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("handling_unit_id");

                    b.Property<decimal>("QtyBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("qty_base");

                    b.Property<decimal>("ReservedQtyBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("reserved_qty_base");

                    b.Property<decimal?>("SecondaryQty")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("secondary_qty");

                    b.HasKey("LocationId", "ArticleId", "HandlingUnitId")
                        .HasName("pk_stock_balance");

                    b.ToTable("stock_balance", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<string>("BaseUomCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("base_uom_code");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid?>("EnteredLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("entered_level_id");

                    b.Property<decimal>("EnteredQty")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("entered_qty");

                    b.Property<Guid?>("EnteredUomId")
                        .HasColumnType("uuid")
                        .HasColumnName("entered_uom_id");

                    b.Property<Guid?>("FromHandlingUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_handling_unit_id");

                    b.Property<Guid?>("FromLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_location_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<decimal>("QtyBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("qty_base");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reference_type");

                    b.Property<decimal?>("SecondaryQty")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("secondary_qty");

                    b.Property<Guid?>("SecondaryUomId")
                        .HasColumnType("uuid")
                        .HasColumnName("secondary_uom_id");

                    b.Property<Guid?>("ToHandlingUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_handling_unit_id");

                    b.Property<Guid?>("ToLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_location_id");

                    b.Property<decimal?>("ToleranceDeltaBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("tolerance_delta_base");

                    b.HasKey("Id")
                        .HasName("pk_stock_movement");

                    b.HasIndex("CommandId")
                        .HasDatabaseName("ix_stock_movement_command_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_stock_movement_occurred_at");

                    b.ToTable("stock_movement", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.TaskLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<Guid?>("FromHandlingUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_handling_unit_id");

                    b.Property<Guid?>("FromLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_location_id");

                    b.Property<decimal>("PickedQtyBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("picked_qty_base");

                    b.Property<decimal>("RequestedQtyBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("requested_qty_base");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SuggestedBreakdown")
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_breakdown");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<decimal?>("TolerancePct")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("tolerance_pct");

                    b.HasKey("Id")
                        .HasName("pk_task_line");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_task_line_task_id");

                    b.ToTable("task_line", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.TenantMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("FeedEpoch")
                        .HasColumnType("uuid")
                        .HasColumnName("feed_epoch");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("schema_version");

                    b.HasKey("Id")
                        .HasName("pk_tenant_meta");

                    b.ToTable("tenant_meta", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("dimension");

                    b.Property<string>("DisplayNameEn")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("display_name_en");

                    b.Property<string>("DisplayNameSv")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("display_name_sv");

                    b.Property<decimal>("FactorToDimensionBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("factor_to_dimension_base");

                    b.HasKey("Id")
                        .HasName("pk_unit_of_measure");

                    b.ToTable("unit_of_measure", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("01900000-0000-7000-8000-000000000101"),
                            Code = "st",
                            Dimension = "count",
                            DisplayNameEn = "st",
                            DisplayNameSv = "st",
                            FactorToDimensionBase = 1m
                        },
                        new
                        {
                            Id = new Guid("01900000-0000-7000-8000-000000000102"),
                            Code = "kg",
                            Dimension = "mass",
                            DisplayNameEn = "kg",
                            DisplayNameSv = "kg",
                            FactorToDimensionBase = 1m
                        },
                        new
                        {
                            Id = new Guid("01900000-0000-7000-8000-000000000103"),
                            Code = "g",
                            Dimension = "mass",
                            DisplayNameEn = "g",
                            DisplayNameSv = "g",
                            FactorToDimensionBase = 0.001m
                        },
                        new
                        {
                            Id = new Guid("01900000-0000-7000-8000-000000000104"),
                            Code = "l",
                            Dimension = "volume",
                            DisplayNameEn = "l",
                            DisplayNameSv = "l",
                            FactorToDimensionBase = 1m
                        },
                        new
                        {
                            Id = new Guid("01900000-0000-7000-8000-000000000105"),
                            Code = "ml",
                            Dimension = "volume",
                            DisplayNameEn = "ml",
                            DisplayNameSv = "ml",
                            FactorToDimensionBase = 0.001m
                        },
                        new
                        {
                            Id = new Guid("01900000-0000-7000-8000-000000000106"),
                            Code = "m",
                            Dimension = "length",
                            DisplayNameEn = "m",
                            DisplayNameSv = "m",
                            FactorToDimensionBase = 1m
                        },
                        new
                        {
                            Id = new Guid("01900000-0000-7000-8000-000000000107"),
                            Code = "cm",
                            Dimension = "length",
                            DisplayNameEn = "cm",
                            DisplayNameSv = "cm",
                            FactorToDimensionBase = 0.01m
                        },
                        new
                        {
                            Id = new Guid("01900000-0000-7000-8000-000000000108"),
                            Code = "m2",
                            Dimension = "area",
                            DisplayNameEn = "m²",
                            DisplayNameSv = "m²",
                            FactorToDimensionBase = 1m
                        },
                        new
                        {
                            Id = new Guid("01900000-0000-7000-8000-000000000109"),
                            Code = "m3",
                            Dimension = "volume",
                            DisplayNameEn = "m³",
                            DisplayNameSv = "m³",
                            FactorToDimensionBase = 1000m
                        });
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<bool>("BlindCount")
                        .HasColumnType("boolean")
                        .HasColumnName("blind_count");

                    b.Property<int>("ClaimMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("claim_minutes");

                    b.Property<string>("CodePattern")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code_pattern");

                    b.Property<decimal?>("CountAutoAdjustThreshold")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("count_auto_adjust_threshold");

                    b.Property<int?>("DefaultDepthMm")
                        .HasColumnType("integer")
                        .HasColumnName("default_depth_mm");

                    b.Property<int?>("DefaultHeightMm")
                        .HasColumnType("integer")
                        .HasColumnName("default_height_mm");

                    b.Property<int?>("DefaultMaxWeightG")
                        .HasColumnType("integer")
                        .HasColumnName("default_max_weight_g");

                    b.Property<int?>("DefaultWidthMm")
                        .HasColumnType("integer")
                        .HasColumnName("default_width_mm");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("NightShift")
                        .HasColumnType("boolean")
                        .HasColumnName("night_shift");

                    b.Property<string>("OperatingHours")
                        .HasColumnType("jsonb")
                        .HasColumnName("operating_hours");

                    b.Property<bool>("PackStep")
                        .HasColumnType("boolean")
                        .HasColumnName("pack_step");

                    b.Property<bool>("ZonePicking")
                        .HasColumnType("boolean")
                        .HasColumnName("zone_picking");

                    b.HasKey("Id")
                        .HasName("pk_warehouse");

                    b.ToTable("warehouse", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.WarehouseTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AssignedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_until");

                    b.Property<Guid?>("AssigneeUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SuggestedLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggested_location_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_task");

                    b.HasIndex("AssignedUntil")
                        .HasDatabaseName("ix_task_assigned_until");

                    b.HasIndex("WarehouseId", "Status")
                        .HasDatabaseName("ix_task_warehouse_id_status");

                    b.ToTable("task", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.Article", b =>
                {
                    b.HasOne("Lagerkraft.WmsCore.Api.Data.UnitOfMeasure", null)
                        .WithMany()
                        .HasForeignKey("BaseUomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_unit_of_measure_base_uom_id");
                });
#pragma warning restore 612, 618
        }
    }
}
