// <auto-generated />
using System;
using Lagerkraft.WmsCore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lagerkraft.WmsCore.Api.Data.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    partial class TenantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.ChangeLogRow", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Seq"));

                    b.Property<Guid?>("Actor")
                        .HasColumnType("uuid")
                        .HasColumnName("actor");

                    b.Property<Guid?>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Op")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("op");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.HasKey("Seq")
                        .HasName("pk_change_log");

                    b.ToTable("change_log", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.Deviation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.HasKey("Id")
                        .HasName("pk_deviation");

                    b.ToTable("deviation", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.OutboxRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_outbox_published_at");

                    b.ToTable("outbox", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.ProcessedCommand", b =>
                {
                    b.Property<Guid>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.HasKey("CommandId")
                        .HasName("pk_processed_commands");

                    b.ToTable("processed_commands", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.ProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Consumer")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("consumer");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.HasKey("EventId", "Consumer")
                        .HasName("pk_processed_events");

                    b.ToTable("processed_events", (string)null);
                });

            modelBuilder.Entity("Lagerkraft.WmsCore.Api.Data.TenantMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("FeedEpoch")
                        .HasColumnType("uuid")
                        .HasColumnName("feed_epoch");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("schema_version");

                    b.HasKey("Id")
                        .HasName("pk_tenant_meta");

                    b.ToTable("tenant_meta", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
